---
- name: Install and start Nginx
  hosts: all
  become: true
  tasks:
    - name: Install Nginx
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: Enable and start Nginx
      ansible.builtin.systemd:
        name: nginx
        enabled: true
        state: started
